"""Copy curated portfolio photos to public/ and emit src/data/portfolio.ts."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "projectphotos"
PUBLIC = ROOT / "public" / "images" / "portfolio"
CURATION = Path(__file__).resolve().parent / "portfolio-curation"

clusters = {c["id"]: c for c in json.loads((CURATION / "clusters.json").read_text(encoding="utf-8"))}

selections = {
    "kitchens": [
        ("cluster-327", "неоклассика", "угловая с островом"),
        ("cluster-139", "неоклассика", "угловая"),
        ("cluster-144", "неоклассика", "прямая"),
        ("cluster-063", "современный", "угловая"),
        ("cluster-102", "современный", "прямая"),
        ("cluster-401", "современный", "П-образная с барной стойкой"),
        ("cluster-357", "современный", "прямая"),
        ("cluster-067", "современный", "угловая"),
    ],
    "hallways": [
        ("cluster-031", "неоклассика", "с зеркалом и сиденьем"),
        ("cluster-145", "классика", "с зеркалом и банкеткой"),
        ("cluster-182", "современный", "с круглым зеркалом"),
        ("cluster-151", "современный", "модульная с рейками"),
        ("cluster-049", "современный", "с мягкой панелью"),
        ("cluster-006", "современный", "с зеркалом"),
        ("cluster-291", "неоклассика", "модульная"),
        ("cluster-360", "классика", "модульная"),
    ],
    "sofas": [
        ("cluster-297", "неоклассика", "прямой"),
        ("cluster-292", "современный", "прямой"),
        ("cluster-257", "неоклассика", "прямой"),
        ("cluster-274", "современный", "прямой"),
        ("cluster-237", "классика", "прямой"),
        ("cluster-245", "классика", "кресло"),
        ("cluster-096", "современный", "прямой"),
        ("cluster-253", "классика", "прямой"),
    ],
}

prefix = {"kitchens": "kitchen", "hallways": "hallway", "sofas": "sofa"}
titles = {"kitchens": "Кухни", "hallways": "Прихожие", "sofas": "Диваны"}
version = "3"

project_groups = []

for cat, items in selections.items():
    collections = []
    for i, (cid, style, layout) in enumerate(items, 1):
        col_id = f"{prefix[cat]}-{i:02d}"
        files = clusters[cid]["files"]
        images = []
        dest_dir = PUBLIC / cat / col_id
        dest_dir.mkdir(parents=True, exist_ok=True)

        for j, fname in enumerate(files, 1):
            src = SRC / fname
            if not src.exists():
                raise FileNotFoundError(src)
            dest_name = f"{j:02d}.jpg"
            shutil.copy2(src, dest_dir / dest_name)
            images.append(f"/images/portfolio/{cat}/{col_id}/{dest_name}?v={version}")

        collections.append(
            {"id": col_id, "style": style, "layout": layout, "images": images}
        )

    cover = collections[0]["images"][0] if collections else ""
    cover_path = PUBLIC / cat / "cover.jpg"
    if collections:
        first_src = SRC / clusters[items[0][0]]["files"][0]
        shutil.copy2(first_src, cover_path)

    project_groups.append(
        {"id": cat, "title": titles[cat], "cover": f"/images/portfolio/{cat}/cover.jpg?v={version}", "collections": collections}
    )

ts = f"""/** Auto-generated by scripts/apply_portfolio.py */

export type ProjectGroupId = "kitchens" | "hallways" | "sofas";

export interface PortfolioCollection {{
  id: string;
  style: string;
  layout: string;
  images: string[];
}}

export interface ProjectGroup {{
  id: ProjectGroupId;
  title: string;
  cover: string;
  collections: PortfolioCollection[];
}}

export const PORTFOLIO_VERSION = "{version}";

export const projectGroups: ProjectGroup[] = {json.dumps(project_groups, ensure_ascii=False, indent=2)};
"""

(ROOT / "src" / "data" / "portfolio.ts").write_text(ts, encoding="utf-8")
print(f"Wrote portfolio.ts with {sum(len(g['collections']) for g in project_groups)} collections")
